# Generated by Django 3.0.5 on 2022-12-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_auto_20221207_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='bloodgroup',
            field=models.CharField(default='NULL', max_length=10),
        ),
    ]
